---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare
          image: sony98/healthcare:5
          ports:
            - containerPort: 8084
          env:
            - name: PORT
              value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: healthcare
